#Your name here

# Makefile for lab 1-4.

#change the last dependency for each new lab
all:  lab3

lab3: lab3.o
	gcc -ansi -pedantic -Wimplicit-function-declaration -Wreturn-type -g -o lab3 lab3.c
	lab3

